language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9

env:
  global:
    - GO15VENDOREXPERIMENT=1
    - APPOPTICS_DEBUG_LEVEL=0
        
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/wadey/gocovmerge
  - go get golang.org/x/net/context github.com/stretchr/testify/assert gopkg.in/mgo.v2/bson
  - go get github.com/opentracing/opentracing-go
  - go get google.golang.org/grpc
  - go get github.com/uluyol/hdrhist

script:
  - cd $GOPATH/src/github.com/librato/go-traceview/v1/tv
  - go build -v github.com/librato/go-traceview/v1/tv github.com/librato/go-traceview/v1/tv/internal/traceview
  - go test -v -covermode=atomic -coverprofile=cov.out -coverpkg github.com/librato/go-traceview/v1/tv/internal/traceview,github.com/librato/go-traceview/v1/tv
  - go test -v -tags disable_tracing -covermode=atomic -coverprofile=covtv.out -coverpkg github.com/librato/go-traceview/v1/tv/internal/traceview,github.com/librato/go-traceview/v1/tv
  - pushd internal/traceview/
  - go test -v -covermode=atomic -coverprofile=cov.out
  - go test -v -tags disable_tracing -covermode=atomic -coverprofile=covtv.out
  - popd
  - pushd ottv
  - go test -v -covermode=atomic -coverprofile=cov.out -coverpkg github.com/librato/go-traceview/v1/tv/internal/traceview,github.com/librato/go-traceview/v1/tv/ottv,github.com/librato/go-traceview/v1/tv
  - go test -v -tags disable_tracing -covermode=atomic -coverprofile=covtv.out -coverpkg github.com/librato/go-traceview/v1/tv/internal/traceview,github.com/librato/go-traceview/v1/tv/ottv,github.com/librato/go-traceview/v1/tv
  - popd
  - gocovmerge cov.out covtv.out internal/traceview/cov.out internal/traceview/covtv.out ottv/cov.out ottv/covtv.out > coverage.txt

after_success:
  - if [[ $TRAVIS_GO_VERSION == 1.9* ]]; then bash <(curl -s https://codecov.io/bash); fi
